version: '3'

services:
  nginx:
    image: cscaetano/teste-nginx
    ports: 
      - "8001:80"
    volumes:
      - ./html:/usr/share/nginx/html
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./mysqldata:/var/lib/mysql
    
